[package]
name = "game-of-life-avx"
version = "0.1.0"
authors = ["Simon Ellmann <simon.ellmann@tum.de>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3"

[lib]
path = "src/main.rs"

[[bench]]
name = "gol_benchmark"
harness = false
