name: Rust

on:
  push:
    branches: [ benchmark ]
  pull_request:
    branches: [ benchmark ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
        env:
          RUSTFLAGS: '-C opt-level=3 -C target-cpu=native'
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUSTFLAGS: '-C opt-level=3 -C target-cpu=native'
      - name: Bench
        uses: actions-rs/cargo@v1
        with:
          command: bench
        env:
          RUSTFLAGS: '-C opt-level=3 -C target-cpu=native'
